@extends('app.app')
@section('title', 'Privacy Policy')
@section('content')
    <h1 style="padding: 0px; margin: 0px 0px 20px; font-size: 30px; font-weight: 700; line-height: 1.2; color: rgb(38, 38, 38); font-family: &quot;Open Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">Privacy Policy</h1>
    <p class="page__text-format_indent" style="padding: 0px; margin: 20px 0px; line-height: 1.7; color: rgb(38, 38, 38); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">Pursuant to our Terms of Use, this document describes how we treat personal information related to your use of this website and the services offered on and through it (the “Service”), including information you provide when using it.</p>
    <p class="page__text-format_indent" style="padding: 0px; margin: 20px 0px; line-height: 1.7; color: rgb(38, 38, 38); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">We do not knowingly seek or collect any personal information or data from persons who have not attained this age.</p>
    <h2 style="padding: 0px; margin: 20px 0px 15px; font-size: 24px; font-weight: 400; line-height: 1.2; color: rgb(38, 38, 38); font-family: &quot;Open Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">Data Collected</h2>
    <p style="padding: 0px; margin: 20px 0px; line-height: 1.7; color: rgb(38, 38, 38); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span class="page__text-format_italic">Using the Service</span>.&nbsp;When you access the Service, use the search function, convert files or download files, your IP address, country of origin and other non-personal information about your computer or device (such as web requests, browser type, browser language, referring URL, operating system and date and time of requests) may be recorded for log file information, aggregated traffic information and in the event that there is any misappropriation of information and/or content.</p>
    <p style="padding: 0px; margin: 20px 0px; line-height: 1.7; color: rgb(38, 38, 38); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span class="page__text-format_italic">Usage Information</span>.&nbsp;We may record information about your usage of the Service such as your search terms, the content you access and download and other statistics.</p>
    <p style="padding: 0px; margin: 20px 0px; line-height: 1.7; color: rgb(38, 38, 38); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span class="page__text-format_italic">Uploaded Content</span>.&nbsp;Any content you upload is not collected by us.</p>
    <p style="padding: 0px; margin: 20px 0px; line-height: 1.7; color: rgb(38, 38, 38); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;"><span class="page__text-format_italic">Cookies</span>.&nbsp;When you use the Service, we may send cookies to your computer to uniquely identify your browser session. We may use both session cookies and persistent cookies.</p>
    <h2 style="padding: 0px; margin: 20px 0px 15px; font-size: 24px; font-weight: 400; line-height: 1.2; color: rgb(38, 38, 38); font-family: &quot;Open Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">Data Usage</h2>
    <p style="padding: 0px; margin: 20px 0px; line-height: 1.7; color: rgb(38, 38, 38); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">We allow third-party companies to serve ads and/or collect certain anonymous information when you visit our web site. </p>
    <h2 style="padding: 0px; margin: 20px 0px 15px; font-size: 24px; font-weight: 400; line-height: 1.2; color: rgb(38, 38, 38); font-family: &quot;Open Sans&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">Miscellaneous</h2>
    <p style="padding: 0px; margin: 20px 0px 0px; line-height: 1.7; color: rgb(38, 38, 38); font-family: &quot;Open Sans&quot;, sans-serif; font-size: 13px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">We may use third-party advertising companies to serve ads when you visit our website</p>
@endsection
<div id="app"></div>
